micronaut:
  application:
    name: kitchenService
  server:
    port: 8889

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:6002/order_service`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:mysecretpassword}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
kafka:
  bootstrap:
    servers: localhost:9093
  acks: all
  key.serializer: org.apache.kafka.common.serialization.StringSerializer
  value.serializer: orders.messaging.OrderSerializer
  max.block.ms: 1000

