micronaut:
  application:
    name: kitchenService

datasources:
  default:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driverClassName: ${JDBC_DRIVER}
kafka:
  bootstrap:
    servers: localhost:9093
  acks: all
  key.serializer: org.apache.kafka.common.serialization.StringSerializer
  value.serializer: orders.messaging.OrderSerializer
  max.block.ms: 1000
flyway:
  datasources:
    default:
      enabled: true

