micronaut:
  application:
    name: accountingService
  server:
    port: 8900

datasources:
  default:
    url: ${JDBC_URL}
    username: ${JDBC_USER}
    password: ${JDBC_PASSWORD}
    driverClassName: ${JDBC_DRIVER}

flyway:
  datasources:
    default:
      enabled: true

kafka:
  bootstrap:
    servers: localhost:9093
  acks: all
  key.serializer: org.apache.kafka.common.serialization.StringSerializer
  value.serializer: mesaging.PaymentPendingSerializer
  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value.deserializer: messaging.PaymentPendingSerializer
  max.block.ms: 1000