micronaut:
  application:
    name: accountingService

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:6004/accounts`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:mysecretpassword}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}
flyway:
  datasources:
    default:
      enabled: true

kafka:
  bootstrap:
    servers: localhost:9093
  acks: all
  key.serializer: org.apache.kafka.common.serialization.StringSerializer
  value.serializer: orders.messaging.OrderSerializer
  max.block.ms: 1000